/**
 * lib/idl/crowdfunding.ts
 *
 * Hand-authored IDL for the crowdfunding Anchor program (see
 * ../../../solana-rust/02-crowdfunding-spl/programs/crowdfunding/src/lib.rs).
 *
 * Why hand-authored instead of generated by `anchor build`?
 * anchor-lang 0.30.1's IDL-generation step hits a real upstream bug
 * (proc_macro2::Span::source_file() was removed in proc-macro2 >=1.0.86,
 * and this project's dependency tree can't pin below that - syn 2.0.119
 * requires proc-macro2 >=1.0.91). The on-chain program itself builds and
 * deploys fine with `anchor build --no-idl`; this file is the IDL that
 * step would have produced, written by hand from the Rust source and
 * verified byte-for-byte against @coral-xyz/anchor's own sighash
 * discriminator computation before being wired in here.
 *
 * All names below are already camelCase (createCampaign, campaignId,
 * contributorTokenAccount, ...) rather than the Rust source's snake_case
 * (create_campaign, campaign_id, ...). Anchor's Program class converts an
 * IDL's names to camelCase at *runtime*, but that conversion isn't
 * reflected in TypeScript's *static* types - the compiler just sees
 * whatever literal string is written here. Writing camelCase directly
 * keeps compile-time types and runtime behavior in agreement. This is
 * purely a labeling/typing concern: byte layout is positional (borsh) and
 * instruction/account identity is the explicit `discriminator` array
 * below, so renaming has zero effect on wire compatibility with the
 * already-deployed program.
 *
 * Two exports, mirroring exactly what `anchor build`'s own TS codegen
 * produces (target/types/crowdfunding.ts in a normal build):
 *   - `Crowdfunding`: a plain (non-`readonly`) literal type describing the
 *     IDL's exact shape, used as the generic parameter to Program<T> so
 *     program.methods.createCampaign / program.account.campaign are
 *     properly typed instead of falling back to `any`.
 *   - `IDL`: the actual runtime object, annotated with that type. (Not
 *     `as const` - `as const` makes every array `readonly`, which
 *     satisfies literal-type inference but then fails Anchor's own `Idl`
 *     type constraint, which declares plain mutable arrays. Using an
 *     explicit type annotation instead of `as const` gives us literal
 *     string/number types WITHOUT the readonly mismatch.)
 */

export type Crowdfunding = {
  address: "6hafcYNa34it4syjPPy8yuQW5LfCmcxhm3D78h2qBA5r";
  metadata: {
    name: "crowdfunding";
    version: "0.1.0";
    spec: "0.1.0";
    description: "SPL-token crowdfunding pools (ported from the ChainFund Solidity contract)";
  };
  instructions: [
    {
      name: "createCampaign";
      discriminator: [111, 131, 187, 98, 160, 193, 114, 244];
      accounts: [
        { name: "creator"; writable: true; signer: true },
        { name: "tokenMint" },
        { name: "campaign"; writable: true },
        { name: "vault"; writable: true },
        { name: "tokenProgram" },
        { name: "systemProgram" },
        { name: "rent" }
      ];
      args: [
        { name: "campaignId"; type: "u64" },
        { name: "title"; type: "string" },
        { name: "description"; type: "string" },
        { name: "imageUrl"; type: "string" },
        { name: "goal"; type: "u64" },
        { name: "durationDays"; type: "i64" }
      ];
    },
    {
      name: "contribute";
      discriminator: [82, 33, 68, 131, 32, 0, 205, 95];
      accounts: [
        { name: "contributor"; writable: true; signer: true },
        { name: "campaign"; writable: true },
        { name: "vault"; writable: true },
        { name: "contribution"; writable: true },
        { name: "contributorTokenAccount"; writable: true },
        { name: "tokenProgram" },
        { name: "systemProgram" }
      ];
      args: [{ name: "amount"; type: "u64" }];
    },
    {
      name: "withdraw";
      discriminator: [183, 18, 70, 156, 148, 109, 161, 34];
      accounts: [
        { name: "creator"; writable: true; signer: true },
        { name: "campaign"; writable: true },
        { name: "vault"; writable: true },
        { name: "tokenMint" },
        { name: "creatorTokenAccount"; writable: true },
        { name: "tokenProgram" },
        { name: "associatedTokenProgram" },
        { name: "systemProgram" },
        { name: "rent" }
      ];
      args: [];
    },
    {
      name: "claimRefund";
      discriminator: [15, 16, 30, 161, 255, 228, 97, 60];
      accounts: [
        { name: "contributor"; writable: true; signer: true },
        { name: "campaign" },
        { name: "vault"; writable: true },
        { name: "contribution"; writable: true },
        { name: "contributorTokenAccount"; writable: true },
        { name: "tokenProgram" }
      ];
      args: [];
    }
  ];
  accounts: [
    { name: "campaign"; discriminator: [50, 40, 49, 11, 157, 220, 229, 192] },
    { name: "contribution"; discriminator: [182, 187, 14, 111, 72, 167, 242, 212] }
  ];
  types: [
    {
      name: "campaign";
      type: {
        kind: "struct";
        fields: [
          { name: "creator"; type: "pubkey" },
          { name: "campaignId"; type: "u64" },
          { name: "title"; type: "string" },
          { name: "description"; type: "string" },
          { name: "imageUrl"; type: "string" },
          { name: "tokenMint"; type: "pubkey" },
          { name: "goal"; type: "u64" },
          { name: "raised"; type: "u64" },
          { name: "deadline"; type: "i64" },
          { name: "withdrawn"; type: "bool" },
          { name: "contributorsCount"; type: "u64" },
          { name: "bump"; type: "u8" },
          { name: "vaultBump"; type: "u8" }
        ];
      };
    },
    {
      name: "contribution";
      type: {
        kind: "struct";
        fields: [
          { name: "campaign"; type: "pubkey" },
          { name: "contributor"; type: "pubkey" },
          { name: "amount"; type: "u64" },
          { name: "lastContributedAt"; type: "i64" },
          { name: "refunded"; type: "bool" },
          { name: "bump"; type: "u8" }
        ];
      };
    }
  ];
  errors: [
    { code: 6000; name: "InvalidTitle"; msg: "Title must be between 5 and 64 characters" },
    { code: 6001; name: "DescriptionTooLong"; msg: "Description must be at most 200 characters" },
    { code: 6002; name: "ImageUrlTooLong"; msg: "Image URL must be at most 200 characters" },
    { code: 6003; name: "InvalidGoal"; msg: "Goal must be greater than zero" },
    { code: 6004; name: "InvalidDuration"; msg: "Duration must be between 1 and 365 days" },
    { code: 6005; name: "ZeroAmount"; msg: "Amount must be greater than zero" },
    { code: 6006; name: "CampaignExpired"; msg: "This campaign's deadline has passed" },
    { code: 6007; name: "NotCreator"; msg: "Only the campaign creator can withdraw" },
    { code: 6008; name: "GoalNotReached"; msg: "The funding goal has not been reached yet" },
    { code: 6009; name: "AlreadyWithdrawn"; msg: "Funds have already been withdrawn" },
    {
      code: 6010;
      name: "CampaignStillActive";
      msg: "Campaign is still active - wait for the deadline to claim a refund";
    },
    {
      code: 6011;
      name: "GoalWasReached";
      msg: "The funding goal was reached - ask the creator to withdraw instead";
    },
    { code: 6012; name: "AlreadyRefunded"; msg: "This contribution has already been refunded" },
    { code: 6013; name: "NothingToRefund"; msg: "Nothing to refund for this contributor" },
    { code: 6014; name: "MathOverflow"; msg: "Math overflow" }
  ];
};

export const IDL: Crowdfunding = {
  address: '6hafcYNa34it4syjPPy8yuQW5LfCmcxhm3D78h2qBA5r',
  metadata: {
    name: 'crowdfunding',
    version: '0.1.0',
    spec: '0.1.0',
    description: 'SPL-token crowdfunding pools (ported from the ChainFund Solidity contract)',
  },
  instructions: [
    {
      name: 'createCampaign',
      discriminator: [111, 131, 187, 98, 160, 193, 114, 244],
      accounts: [
        { name: 'creator', writable: true, signer: true },
        { name: 'tokenMint' },
        { name: 'campaign', writable: true },
        { name: 'vault', writable: true },
        { name: 'tokenProgram' },
        { name: 'systemProgram' },
        { name: 'rent' },
      ],
      args: [
        { name: 'campaignId', type: 'u64' },
        { name: 'title', type: 'string' },
        { name: 'description', type: 'string' },
        { name: 'imageUrl', type: 'string' },
        { name: 'goal', type: 'u64' },
        { name: 'durationDays', type: 'i64' },
      ],
    },
    {
      name: 'contribute',
      discriminator: [82, 33, 68, 131, 32, 0, 205, 95],
      accounts: [
        { name: 'contributor', writable: true, signer: true },
        { name: 'campaign', writable: true },
        { name: 'vault', writable: true },
        { name: 'contribution', writable: true },
        { name: 'contributorTokenAccount', writable: true },
        { name: 'tokenProgram' },
        { name: 'systemProgram' },
      ],
      args: [{ name: 'amount', type: 'u64' }],
    },
    {
      name: 'withdraw',
      discriminator: [183, 18, 70, 156, 148, 109, 161, 34],
      accounts: [
        { name: 'creator', writable: true, signer: true },
        { name: 'campaign', writable: true },
        { name: 'vault', writable: true },
        { name: 'tokenMint' },
        { name: 'creatorTokenAccount', writable: true },
        { name: 'tokenProgram' },
        { name: 'associatedTokenProgram' },
        { name: 'systemProgram' },
        { name: 'rent' },
      ],
      args: [],
    },
    {
      name: 'claimRefund',
      discriminator: [15, 16, 30, 161, 255, 228, 97, 60],
      accounts: [
        { name: 'contributor', writable: true, signer: true },
        { name: 'campaign' },
        { name: 'vault', writable: true },
        { name: 'contribution', writable: true },
        { name: 'contributorTokenAccount', writable: true },
        { name: 'tokenProgram' },
      ],
      args: [],
    },
  ],
  accounts: [
    { name: 'campaign', discriminator: [50, 40, 49, 11, 157, 220, 229, 192] },
    { name: 'contribution', discriminator: [182, 187, 14, 111, 72, 167, 242, 212] },
  ],
  types: [
    {
      name: 'campaign',
      type: {
        kind: 'struct',
        fields: [
          { name: 'creator', type: 'pubkey' },
          { name: 'campaignId', type: 'u64' },
          { name: 'title', type: 'string' },
          { name: 'description', type: 'string' },
          { name: 'imageUrl', type: 'string' },
          { name: 'tokenMint', type: 'pubkey' },
          { name: 'goal', type: 'u64' },
          { name: 'raised', type: 'u64' },
          { name: 'deadline', type: 'i64' },
          { name: 'withdrawn', type: 'bool' },
          { name: 'contributorsCount', type: 'u64' },
          { name: 'bump', type: 'u8' },
          { name: 'vaultBump', type: 'u8' },
        ],
      },
    },
    {
      name: 'contribution',
      type: {
        kind: 'struct',
        fields: [
          { name: 'campaign', type: 'pubkey' },
          { name: 'contributor', type: 'pubkey' },
          { name: 'amount', type: 'u64' },
          { name: 'lastContributedAt', type: 'i64' },
          { name: 'refunded', type: 'bool' },
          { name: 'bump', type: 'u8' },
        ],
      },
    },
  ],
  errors: [
    { code: 6000, name: 'InvalidTitle', msg: 'Title must be between 5 and 64 characters' },
    { code: 6001, name: 'DescriptionTooLong', msg: 'Description must be at most 200 characters' },
    { code: 6002, name: 'ImageUrlTooLong', msg: 'Image URL must be at most 200 characters' },
    { code: 6003, name: 'InvalidGoal', msg: 'Goal must be greater than zero' },
    { code: 6004, name: 'InvalidDuration', msg: 'Duration must be between 1 and 365 days' },
    { code: 6005, name: 'ZeroAmount', msg: 'Amount must be greater than zero' },
    { code: 6006, name: 'CampaignExpired', msg: "This campaign's deadline has passed" },
    { code: 6007, name: 'NotCreator', msg: 'Only the campaign creator can withdraw' },
    { code: 6008, name: 'GoalNotReached', msg: 'The funding goal has not been reached yet' },
    { code: 6009, name: 'AlreadyWithdrawn', msg: 'Funds have already been withdrawn' },
    {
      code: 6010,
      name: 'CampaignStillActive',
      msg: "Campaign is still active - wait for the deadline to claim a refund",
    },
    {
      code: 6011,
      name: 'GoalWasReached',
      msg: 'The funding goal was reached - ask the creator to withdraw instead',
    },
    { code: 6012, name: 'AlreadyRefunded', msg: 'This contribution has already been refunded' },
    { code: 6013, name: 'NothingToRefund', msg: 'Nothing to refund for this contributor' },
    { code: 6014, name: 'MathOverflow', msg: 'Math overflow' },
  ],
}
